/**
 * Canonical Experience catalog — single source of truth.
 *
 * Wave 14A foundation + Wave 15AC Experience Contracts on every entry.
 * Departments select from this catalog; they do not invent executable IDs.
 * No UI, Projection, Shell, or runtime consumers in this wave.
 */

import { defineExperience } from "./define-experience";
import type { ExperienceDefinition } from "./types";

/**
 * Ordered catalog. Order is the default catalog enumeration order.
 * Department-specific display order comes from Operational Areas.
 */
export const EXPERIENCE_CATALOG: readonly ExperienceDefinition[] = [
  // -------------------------------------------------------------------------
  // Service (Dietary)
  // -------------------------------------------------------------------------
  defineExperience({
    key: "MEAL_SERVICE",
    name: "Meal Service",
    description: "Serving meals to residents and patients at the point of service.",
    departments: ["DIETARY"],
    icon: "menus",
    tools: ["TASKS", "RECORDS", "LOGS"],
    category: "SERVICE",
    contract: {
      domains: ["meal_service", "operations"],
      grain: "ROOM",
      includeStatus: true,
      includeOutstandingWork: true,
      includeResources: false,
      includeHistory: true,
      includeMetrics: true,
      includeAi: true,
      relatedExperienceKeys: [
        "MEAL_TIMES",
        "TEMPERATURE_MONITORING",
        "TRAY_ACCURACY",
        "PRODUCTION",
      ],
      configurationSchema: {
        supportedMealPeriods: { type: "string[]" },
      },
    },
  }),
  defineExperience({
    key: "MEAL_TIMES",
    name: "Meal Times",
    description: "Meal period schedule and service timing for the facility day.",
    departments: ["DIETARY"],
    icon: "todaysWork",
    tools: ["RECORDS"],
    category: "SERVICE",
    contract: {
      domains: ["meal_times", "operations"],
      grain: "FACILITY",
      includeStatus: true,
      includeOutstandingWork: false,
      includeHistory: true,
      relatedExperienceKeys: ["MEAL_SERVICE"],
    },
  }),
  defineExperience({
    key: "MENUS",
    name: "Menus",
    description: "Menu planning, cycles, and dietary menu publication.",
    departments: ["DIETARY"],
    icon: "menus",
    tools: ["RECORDS", "KNOWLEDGE"],
    category: "SERVICE",
    contract: {
      domains: ["menus"],
      grain: "DEPARTMENT",
      includeStatus: false,
      includeOutstandingWork: false,
      includeHistory: true,
      relatedExperienceKeys: ["RECIPES", "MEAL_SERVICE"],
    },
  }),
  defineExperience({
    key: "RECIPES",
    name: "Recipes",
    description: "Recipe standards used for production and service.",
    departments: ["DIETARY"],
    icon: "locationKitchen",
    tools: ["KNOWLEDGE", "RECORDS"],
    category: "SERVICE",
    contract: {
      domains: ["recipes"],
      grain: "DEPARTMENT",
      includeStatus: false,
      includeOutstandingWork: false,
      includeHistory: false,
      relatedExperienceKeys: ["MENUS", "PRODUCTION"],
    },
  }),
  defineExperience({
    key: "PRODUCTION",
    name: "Production",
    description: "Food production execution and batch output.",
    departments: ["DIETARY"],
    icon: "locationKitchen",
    tools: ["TASKS", "LOGS", "RECORDS"],
    category: "PRODUCTION",
    contract: {
      domains: ["production", "batch_records"],
      grain: "UNIT",
      includeStatus: true,
      includeOutstandingWork: true,
      includeHistory: true,
      relatedExperienceKeys: ["BATCH_RECORDS", "FORECASTING", "MEAL_SERVICE"],
    },
  }),
  defineExperience({
    key: "NOURISHMENTS",
    name: "Nourishments",
    description: "Between-meal nourishment programs and delivery.",
    departments: ["DIETARY"],
    icon: "menus",
    tools: ["TASKS", "LOGS", "RECORDS"],
    category: "SERVICE",
    contract: {
      domains: ["nourishments"],
      grain: "ROOM",
      includeStatus: true,
      includeOutstandingWork: true,
      relatedExperienceKeys: ["MEAL_SERVICE"],
    },
  }),
  defineExperience({
    key: "TRAY_ACCURACY",
    name: "Tray Accuracy",
    description: "Verification that trays match ordered diets and preferences.",
    departments: ["DIETARY"],
    icon: "review",
    tools: ["TASKS", "LOGS", "RECORDS"],
    category: "QUALITY",
    contract: {
      domains: ["tray_accuracy"],
      grain: "ROOM",
      includeStatus: true,
      includeOutstandingWork: true,
      includeMetrics: true,
      relatedExperienceKeys: ["MEAL_SERVICE", "WORK_ORDERS"],
    },
  }),

  // -------------------------------------------------------------------------
  // Food Safety (Dietary)
  // -------------------------------------------------------------------------
  defineExperience({
    key: "TEMPERATURE_MONITORING",
    name: "Temperature Monitoring",
    description: "Temperature checks for holding, storage, and service.",
    departments: ["DIETARY"],
    icon: "logs",
    tools: ["LOGS", "FORMS", "RECORDS", "TASKS"],
    category: "FOOD_SAFETY",
    contract: {
      domains: ["temperature_logs", "food_safety"],
      grain: "ROOM",
      includeStatus: true,
      includeOutstandingWork: true,
      includeResources: true,
      includeHistory: true,
      includeMetrics: true,
      includeAi: true,
      relatedExperienceKeys: ["SANITATION", "HACCP", "CORRECTIVE_ACTIONS", "MEAL_SERVICE"],
      configurationSchema: {
        thresholdProfile: { type: "string" },
        templateBindings: { type: "string[]" },
      },
      extraAnalyticsKeys: [
        "temperature_monitoring.overdue_count",
        "temperature_monitoring.compliance_rate",
      ],
      extraAiContextKeys: [
        "temperature_monitoring.knowledge",
        "temperature_monitoring.recommendations",
      ],
    },
  }),
  defineExperience({
    key: "SANITATION",
    name: "Sanitation",
    description: "Sanitation standards and verification for food-service spaces.",
    departments: ["DIETARY"],
    icon: "logs",
    tools: ["LOGS", "FORMS", "KNOWLEDGE", "TASKS"],
    category: "FOOD_SAFETY",
    contract: {
      domains: ["sanitation", "food_safety"],
      grain: "ROOM",
      includeStatus: true,
      includeOutstandingWork: true,
      relatedExperienceKeys: ["TEMPERATURE_MONITORING", "CLEANING"],
    },
  }),
  defineExperience({
    key: "HACCP",
    name: "HACCP",
    description: "Hazard analysis and critical control point programs.",
    departments: ["DIETARY"],
    icon: "administration",
    tools: ["FORMS", "KNOWLEDGE", "RECORDS", "LOGS"],
    category: "FOOD_SAFETY",
    contract: {
      domains: ["haccp", "food_safety"],
      grain: "DEPARTMENT",
      includeStatus: true,
      includeOutstandingWork: true,
      includeAi: true,
      relatedExperienceKeys: ["TEMPERATURE_MONITORING", "CORRECTIVE_ACTIONS"],
    },
  }),
  defineExperience({
    key: "CORRECTIVE_ACTIONS",
    name: "Corrective Actions",
    description: "Food-safety corrective actions and follow-through.",
    departments: ["DIETARY"],
    icon: "warning",
    tools: ["TASKS", "FORMS", "RECORDS"],
    category: "FOOD_SAFETY",
    contract: {
      domains: ["corrective_actions", "food_safety"],
      grain: "ROOM",
      includeStatus: true,
      includeOutstandingWork: true,
      relatedExperienceKeys: ["TEMPERATURE_MONITORING", "HACCP"],
    },
  }),

  // -------------------------------------------------------------------------
  // Cleaning / Room Status
  // -------------------------------------------------------------------------
  defineExperience({
    key: "CLEANING",
    name: "Cleaning",
    description: "Cleaning execution across resident, public, and service spaces.",
    departments: ["EVS", "DIETARY"],
    icon: "logs",
    tools: ["TASKS", "LOGS", "FORMS", "RECORDS"],
    category: "CLEANING",
    contract: {
      domains: ["cleaning"],
      grain: "ROOM",
      includeStatus: true,
      includeOutstandingWork: true,
      includeHistory: true,
      includeMetrics: true,
      includeAi: true,
      relatedExperienceKeys: ["CLEANING_LISTS", "ROOM_CLEANING", "ROOM_STATUS"],
    },
  }),
  defineExperience({
    key: "CLEANING_LISTS",
    name: "Cleaning Lists",
    description: "Structured cleaning checklists and list-driven rounds.",
    departments: ["EVS", "DIETARY"],
    icon: "logs",
    tools: ["FORMS", "TASKS", "RECORDS"],
    category: "CLEANING",
    contract: {
      domains: ["cleaning_lists"],
      grain: "ROOM",
      includeStatus: true,
      includeOutstandingWork: true,
      relatedExperienceKeys: ["CLEANING"],
    },
  }),
  defineExperience({
    key: "ROOM_CLEANING",
    name: "Room Cleaning",
    description: "Daily and routine cleaning of occupied rooms.",
    departments: ["EVS"],
    icon: "locations",
    tools: ["TASKS", "LOGS", "RECORDS"],
    category: "CLEANING",
    contract: {
      domains: ["room_cleaning"],
      grain: "ROOM",
      includeStatus: true,
      includeOutstandingWork: true,
      relatedExperienceKeys: ["ROOM_STATUS", "CLEANING"],
    },
  }),
  defineExperience({
    key: "PROJECT_CLEANING",
    name: "Project Cleaning",
    description: "Project and deep-cleaning programs for public and specialty areas.",
    departments: ["EVS"],
    icon: "locations",
    tools: ["TASKS", "FORMS", "RECORDS"],
    category: "CLEANING",
    contract: {
      domains: ["project_cleaning"],
      grain: "UNIT",
      includeStatus: true,
      includeOutstandingWork: true,
      relatedExperienceKeys: ["CLEANING"],
    },
  }),
  defineExperience({
    key: "ROOM_STATUS",
    name: "Room Status",
    description: "Bed and room readiness, turnover, and status tracking.",
    departments: ["EVS"],
    icon: "locations",
    tools: ["TASKS", "RECORDS", "LOGS"],
    category: "ROOM_STATUS",
    contract: {
      domains: ["room_status"],
      grain: "ROOM",
      includeStatus: true,
      includeOutstandingWork: true,
      relatedExperienceKeys: ["ROOM_CLEANING"],
    },
  }),

  // -------------------------------------------------------------------------
  // Equipment / Assets
  // -------------------------------------------------------------------------
  defineExperience({
    key: "EQUIPMENT",
    name: "Equipment",
    description:
      "Department equipment awareness, care, and issue reporting (food service, EVS).",
    departments: ["DIETARY", "EVS"],
    icon: "assets",
    tools: ["TASKS", "RECORDS", "KNOWLEDGE", "LOGS"],
    category: "EQUIPMENT",
    contract: {
      domains: ["equipment"],
      grain: "ROOM",
      includeStatus: true,
      includeOutstandingWork: true,
      includeResources: true,
      relatedExperienceKeys: ["ASSETS", "WORK_ORDERS"],
    },
  }),
  defineExperience({
    key: "ASSETS",
    name: "Assets",
    description: "Tracked physical asset registry, condition, and lifecycle.",
    departments: ["PLANT", "DIETARY", "EVS"],
    icon: "assets",
    tools: ["RECORDS", "KNOWLEDGE", "FORMS", "TASKS"],
    category: "ASSETS",
    contract: {
      domains: ["assets"],
      grain: "FACILITY",
      includeStatus: true,
      includeOutstandingWork: true,
      includeResources: true,
      includeHistory: true,
      relatedExperienceKeys: ["PREVENTIVE_MAINTENANCE", "WORK_ORDERS", "EQUIPMENT"],
    },
  }),

  // -------------------------------------------------------------------------
  // Maintenance / Work Orders / Utilities (Plant)
  // -------------------------------------------------------------------------
  defineExperience({
    key: "WORK_ORDERS",
    name: "Work Orders",
    description: "Reactive repairs, requests, and maintenance work orders.",
    departments: ["PLANT", "DIETARY"],
    icon: "repairs",
    tools: ["TASKS", "RECORDS", "FORMS", "KNOWLEDGE"],
    category: "MAINTENANCE",
    contract: {
      domains: ["work_orders", "repairs"],
      grain: "ROOM",
      includeStatus: true,
      includeOutstandingWork: true,
      includeHistory: true,
      includeAi: true,
      relatedExperienceKeys: ["ASSETS", "PREVENTIVE_MAINTENANCE"],
    },
  }),
  defineExperience({
    key: "PREVENTIVE_MAINTENANCE",
    name: "Preventive Maintenance",
    description: "Scheduled preventive maintenance programs and rounds.",
    departments: ["PLANT"],
    icon: "todaysWork",
    tools: ["TASKS", "LOGS", "FORMS", "RECORDS", "KNOWLEDGE"],
    category: "MAINTENANCE",
    contract: {
      domains: ["preventive_maintenance"],
      grain: "ROOM",
      includeStatus: true,
      includeOutstandingWork: true,
      includeResources: true,
      includeHistory: true,
      includeMetrics: true,
      relatedExperienceKeys: ["ASSETS", "WORK_ORDERS"],
    },
  }),
  defineExperience({
    key: "UTILITIES",
    name: "Utilities",
    description: "Facility utilities including generators, boilers, and water systems.",
    departments: ["PLANT"],
    icon: "facility",
    tools: ["LOGS", "TASKS", "RECORDS", "KNOWLEDGE"],
    category: "UTILITIES",
    contract: {
      domains: ["utilities"],
      grain: "FACILITY",
      includeStatus: true,
      includeOutstandingWork: true,
      includeResources: true,
      relatedExperienceKeys: ["LIFE_SAFETY", "ASSETS"],
    },
  }),

  // -------------------------------------------------------------------------
  // People
  // -------------------------------------------------------------------------
  defineExperience({
    key: "ASSIGNMENTS",
    name: "Assignments",
    description: "Assigning operational work to people for the facility day.",
    departments: ["DIETARY", "EVS", "PLANT"],
    icon: "employees",
    tools: ["TASKS", "RECORDS"],
    category: "PEOPLE",
    contract: {
      domains: ["assignments"],
      grain: "DEPARTMENT",
      includeStatus: true,
      includeOutstandingWork: true,
      relatedExperienceKeys: ["SCHEDULING"],
    },
  }),
  defineExperience({
    key: "SCHEDULING",
    name: "Scheduling",
    description: "Staff scheduling patterns and coverage for the department.",
    departments: ["DIETARY", "EVS", "PLANT"],
    icon: "todaysWork",
    tools: ["RECORDS", "FORMS"],
    category: "PEOPLE",
    contract: {
      domains: ["scheduling"],
      grain: "DEPARTMENT",
      includeStatus: true,
      includeOutstandingWork: true,
      relatedExperienceKeys: ["ASSIGNMENTS"],
    },
  }),
  defineExperience({
    key: "COMPETENCIES",
    name: "Competencies",
    description: "Competency tracking and certification adjacent to staffing.",
    departments: ["DIETARY", "EVS", "PLANT"],
    icon: "employees",
    tools: ["RECORDS", "FORMS", "KNOWLEDGE"],
    category: "PEOPLE",
    contract: {
      domains: ["competencies"],
      grain: "DEPARTMENT",
      includeStatus: false,
      includeOutstandingWork: false,
      includeHistory: true,
      relatedExperienceKeys: ["SCHEDULING"],
    },
  }),

  // -------------------------------------------------------------------------
  // Production extras
  // -------------------------------------------------------------------------
  defineExperience({
    key: "FORECASTING",
    name: "Forecasting",
    description: "Production forecasting for meal and batch planning.",
    departments: ["DIETARY"],
    icon: "review",
    tools: ["RECORDS", "FORMS"],
    category: "PRODUCTION",
    contract: {
      domains: ["forecasting"],
      grain: "DEPARTMENT",
      includeStatus: false,
      includeOutstandingWork: false,
      includeMetrics: true,
      relatedExperienceKeys: ["PRODUCTION", "BATCH_RECORDS"],
    },
  }),
  defineExperience({
    key: "BATCH_RECORDS",
    name: "Batch Records",
    description: "Batch production records and yield documentation.",
    departments: ["DIETARY"],
    icon: "logs",
    tools: ["RECORDS", "LOGS", "FORMS"],
    category: "PRODUCTION",
    contract: {
      domains: ["batch_records"],
      grain: "UNIT",
      includeStatus: true,
      includeOutstandingWork: true,
      includeHistory: true,
      relatedExperienceKeys: ["PRODUCTION"],
    },
  }),

  // -------------------------------------------------------------------------
  // Quality / Compliance
  // -------------------------------------------------------------------------
  defineExperience({
    key: "ROUNDING",
    name: "Rounding",
    description: "Structured supervisory and quality walkthroughs.",
    departments: ["DIETARY", "EVS", "PLANT"],
    icon: "review",
    tools: ["FORMS", "TASKS", "RECORDS", "LOGS"],
    category: "QUALITY",
    contract: {
      domains: ["rounding"],
      grain: "UNIT",
      includeStatus: true,
      includeOutstandingWork: true,
      relatedExperienceKeys: ["AUDITS"],
    },
  }),
  defineExperience({
    key: "SATISFACTION",
    name: "Satisfaction",
    description: "Resident and guest satisfaction capture related to service.",
    departments: ["DIETARY"],
    icon: "review",
    tools: ["FORMS", "RECORDS"],
    category: "QUALITY",
    contract: {
      domains: ["satisfaction"],
      grain: "DEPARTMENT",
      includeStatus: false,
      includeOutstandingWork: false,
      includeMetrics: true,
      relatedExperienceKeys: ["MEAL_SERVICE"],
    },
  }),
  defineExperience({
    key: "AUDITS",
    name: "Audits",
    description: "Compliance and quality audits across department areas.",
    departments: ["DIETARY", "EVS", "PLANT"],
    icon: "administration",
    tools: ["FORMS", "RECORDS", "TASKS", "KNOWLEDGE"],
    category: "COMPLIANCE",
    contract: {
      domains: ["audits"],
      grain: "DEPARTMENT",
      includeStatus: true,
      includeOutstandingWork: true,
      includeHistory: true,
      relatedExperienceKeys: ["INSPECTIONS", "ROUNDING"],
    },
  }),
  defineExperience({
    key: "INSPECTIONS",
    name: "Inspections",
    description: "Inspection programs, occurrences, and submissions.",
    departments: ["DIETARY", "EVS", "PLANT"],
    icon: "administration",
    tools: ["FORMS", "RECORDS", "TASKS", "LOGS"],
    category: "COMPLIANCE",
    contract: {
      domains: ["inspections"],
      grain: "ROOM",
      includeStatus: true,
      includeOutstandingWork: true,
      includeHistory: true,
      relatedExperienceKeys: ["AUDITS", "WORK_ORDERS"],
    },
  }),
  defineExperience({
    key: "INFECTION_CONTROL",
    name: "Infection Control",
    description: "Infection-control practices and verification for EVS.",
    departments: ["EVS"],
    icon: "administration",
    tools: ["FORMS", "KNOWLEDGE", "LOGS", "TASKS"],
    category: "COMPLIANCE",
    contract: {
      domains: ["infection_control"],
      grain: "ROOM",
      includeStatus: true,
      includeOutstandingWork: true,
      relatedExperienceKeys: ["CLEANING", "ROOM_STATUS"],
    },
  }),
  defineExperience({
    key: "LIFE_SAFETY",
    name: "Life Safety",
    description: "Life-safety compliance rounds and documentation for Plant.",
    departments: ["PLANT"],
    icon: "administration",
    tools: ["LOGS", "FORMS", "RECORDS", "TASKS", "KNOWLEDGE"],
    category: "COMPLIANCE",
    contract: {
      domains: ["life_safety"],
      grain: "FACILITY",
      includeStatus: true,
      includeOutstandingWork: true,
      includeHistory: true,
      relatedExperienceKeys: ["UTILITIES", "INSPECTIONS"],
    },
  }),
];
