/**
 * Canonical Experience catalog — single source of truth.
 *
 * Wave 14A foundation. Departments select from this catalog; they do not
 * invent executable Experience IDs. No UI, Projection, or runtime consumers yet.
 */

import type { ExperienceDefinition } from "./types";

/**
 * Ordered catalog. Order is the default catalog enumeration order.
 * Department-specific display order comes from Operational Areas.
 */
export const EXPERIENCE_CATALOG: readonly ExperienceDefinition[] = [
  // -------------------------------------------------------------------------
  // Service (Dietary)
  // -------------------------------------------------------------------------
  {
    id: "MEAL_SERVICE",
    key: "MEAL_SERVICE",
    name: "Meal Service",
    description: "Serving meals to residents and patients at the point of service.",
    departments: ["DIETARY"],
    icon: "menus",
    status: "active",
    tools: ["TASKS", "RECORDS", "LOGS"],
    category: "SERVICE",
    version: 1,
  },
  {
    id: "MEAL_TIMES",
    key: "MEAL_TIMES",
    name: "Meal Times",
    description: "Meal period schedule and service timing for the facility day.",
    departments: ["DIETARY"],
    icon: "todaysWork",
    status: "active",
    tools: ["RECORDS"],
    category: "SERVICE",
    version: 1,
  },
  {
    id: "MENUS",
    key: "MENUS",
    name: "Menus",
    description: "Menu planning, cycles, and dietary menu publication.",
    departments: ["DIETARY"],
    icon: "menus",
    status: "active",
    tools: ["RECORDS", "KNOWLEDGE"],
    category: "SERVICE",
    version: 1,
  },
  {
    id: "RECIPES",
    key: "RECIPES",
    name: "Recipes",
    description: "Recipe standards used for production and service.",
    departments: ["DIETARY"],
    icon: "locationKitchen",
    status: "active",
    tools: ["KNOWLEDGE", "RECORDS"],
    category: "SERVICE",
    version: 1,
  },
  {
    id: "PRODUCTION",
    key: "PRODUCTION",
    name: "Production",
    description: "Food production execution and batch output.",
    departments: ["DIETARY"],
    icon: "locationKitchen",
    status: "active",
    tools: ["TASKS", "LOGS", "RECORDS"],
    category: "PRODUCTION",
    version: 1,
  },
  {
    id: "NOURISHMENTS",
    key: "NOURISHMENTS",
    name: "Nourishments",
    description: "Between-meal nourishment programs and delivery.",
    departments: ["DIETARY"],
    icon: "menus",
    status: "active",
    tools: ["TASKS", "LOGS", "RECORDS"],
    category: "SERVICE",
    version: 1,
  },
  {
    id: "TRAY_ACCURACY",
    key: "TRAY_ACCURACY",
    name: "Tray Accuracy",
    description: "Verification that trays match ordered diets and preferences.",
    departments: ["DIETARY"],
    icon: "review",
    status: "active",
    tools: ["TASKS", "LOGS", "RECORDS"],
    category: "QUALITY",
    version: 1,
  },

  // -------------------------------------------------------------------------
  // Food Safety (Dietary)
  // -------------------------------------------------------------------------
  {
    id: "TEMPERATURE_MONITORING",
    key: "TEMPERATURE_MONITORING",
    name: "Temperature Monitoring",
    description: "Temperature checks for holding, storage, and service.",
    departments: ["DIETARY"],
    icon: "logs",
    status: "active",
    tools: ["LOGS", "FORMS", "RECORDS", "TASKS"],
    category: "FOOD_SAFETY",
    version: 1,
  },
  {
    id: "SANITATION",
    key: "SANITATION",
    name: "Sanitation",
    description: "Sanitation standards and verification for food-service spaces.",
    departments: ["DIETARY"],
    icon: "logs",
    status: "active",
    tools: ["LOGS", "FORMS", "KNOWLEDGE", "TASKS"],
    category: "FOOD_SAFETY",
    version: 1,
  },
  {
    id: "HACCP",
    key: "HACCP",
    name: "HACCP",
    description: "Hazard analysis and critical control point programs.",
    departments: ["DIETARY"],
    icon: "administration",
    status: "active",
    tools: ["FORMS", "KNOWLEDGE", "RECORDS", "LOGS"],
    category: "FOOD_SAFETY",
    version: 1,
  },
  {
    id: "CORRECTIVE_ACTIONS",
    key: "CORRECTIVE_ACTIONS",
    name: "Corrective Actions",
    description: "Food-safety corrective actions and follow-through.",
    departments: ["DIETARY"],
    icon: "warning",
    status: "active",
    tools: ["TASKS", "FORMS", "RECORDS"],
    category: "FOOD_SAFETY",
    version: 1,
  },

  // -------------------------------------------------------------------------
  // Cleaning / Room Status (EVS + Dietary where self-cleaning)
  // -------------------------------------------------------------------------
  {
    id: "CLEANING",
    key: "CLEANING",
    name: "Cleaning",
    description: "Cleaning execution across resident, public, and service spaces.",
    departments: ["EVS", "DIETARY"],
    icon: "logs",
    status: "active",
    tools: ["TASKS", "LOGS", "FORMS", "RECORDS"],
    category: "CLEANING",
    version: 1,
  },
  {
    id: "CLEANING_LISTS",
    key: "CLEANING_LISTS",
    name: "Cleaning Lists",
    description: "Structured cleaning checklists and list-driven rounds.",
    departments: ["EVS", "DIETARY"],
    icon: "logs",
    status: "active",
    tools: ["FORMS", "TASKS", "RECORDS"],
    category: "CLEANING",
    version: 1,
  },
  {
    id: "ROOM_CLEANING",
    key: "ROOM_CLEANING",
    name: "Room Cleaning",
    description: "Daily and routine cleaning of occupied rooms.",
    departments: ["EVS"],
    icon: "locations",
    status: "active",
    tools: ["TASKS", "LOGS", "RECORDS"],
    category: "CLEANING",
    version: 1,
  },
  {
    id: "PROJECT_CLEANING",
    key: "PROJECT_CLEANING",
    name: "Project Cleaning",
    description: "Project and deep-cleaning programs for public and specialty areas.",
    departments: ["EVS"],
    icon: "locations",
    status: "active",
    tools: ["TASKS", "FORMS", "RECORDS"],
    category: "CLEANING",
    version: 1,
  },
  {
    id: "ROOM_STATUS",
    key: "ROOM_STATUS",
    name: "Room Status",
    description: "Bed and room readiness, turnover, and status tracking.",
    departments: ["EVS"],
    icon: "locations",
    status: "active",
    tools: ["TASKS", "RECORDS", "LOGS"],
    category: "ROOM_STATUS",
    version: 1,
  },

  // -------------------------------------------------------------------------
  // Equipment / Assets
  // -------------------------------------------------------------------------
  {
    id: "EQUIPMENT",
    key: "EQUIPMENT",
    name: "Equipment",
    description:
      "Department equipment awareness, care, and issue reporting (food service, EVS).",
    departments: ["DIETARY", "EVS"],
    icon: "assets",
    status: "active",
    tools: ["TASKS", "RECORDS", "KNOWLEDGE", "LOGS"],
    category: "EQUIPMENT",
    version: 1,
  },
  {
    id: "ASSETS",
    key: "ASSETS",
    name: "Assets",
    description: "Tracked physical asset registry, condition, and lifecycle.",
    departments: ["PLANT", "DIETARY", "EVS"],
    icon: "assets",
    status: "active",
    tools: ["RECORDS", "KNOWLEDGE", "FORMS", "TASKS"],
    category: "ASSETS",
    version: 1,
  },

  // -------------------------------------------------------------------------
  // Maintenance / Work Orders / Utilities (Plant)
  // -------------------------------------------------------------------------
  {
    id: "WORK_ORDERS",
    key: "WORK_ORDERS",
    name: "Work Orders",
    description: "Reactive repairs, requests, and maintenance work orders.",
    departments: ["PLANT", "DIETARY"],
    icon: "repairs",
    status: "active",
    tools: ["TASKS", "RECORDS", "FORMS", "KNOWLEDGE"],
    category: "MAINTENANCE",
    version: 1,
  },
  {
    id: "PREVENTIVE_MAINTENANCE",
    key: "PREVENTIVE_MAINTENANCE",
    name: "Preventive Maintenance",
    description: "Scheduled preventive maintenance programs and rounds.",
    departments: ["PLANT"],
    icon: "todaysWork",
    status: "active",
    tools: ["TASKS", "LOGS", "FORMS", "RECORDS", "KNOWLEDGE"],
    category: "MAINTENANCE",
    version: 1,
  },
  {
    id: "UTILITIES",
    key: "UTILITIES",
    name: "Utilities",
    description: "Facility utilities including generators, boilers, and water systems.",
    departments: ["PLANT"],
    icon: "facility",
    status: "active",
    tools: ["LOGS", "TASKS", "RECORDS", "KNOWLEDGE"],
    category: "UTILITIES",
    version: 1,
  },

  // -------------------------------------------------------------------------
  // People (all departments)
  // -------------------------------------------------------------------------
  {
    id: "ASSIGNMENTS",
    key: "ASSIGNMENTS",
    name: "Assignments",
    description: "Assigning operational work to people for the facility day.",
    departments: ["DIETARY", "EVS", "PLANT"],
    icon: "employees",
    status: "active",
    tools: ["TASKS", "RECORDS"],
    category: "PEOPLE",
    version: 1,
  },
  {
    id: "SCHEDULING",
    key: "SCHEDULING",
    name: "Scheduling",
    description: "Staff scheduling patterns and coverage for the department.",
    departments: ["DIETARY", "EVS", "PLANT"],
    icon: "todaysWork",
    status: "active",
    tools: ["RECORDS", "FORMS"],
    category: "PEOPLE",
    version: 1,
  },
  {
    id: "COMPETENCIES",
    key: "COMPETENCIES",
    name: "Competencies",
    description: "Competency tracking and certification adjacent to staffing.",
    departments: ["DIETARY", "EVS", "PLANT"],
    icon: "employees",
    status: "active",
    tools: ["RECORDS", "FORMS", "KNOWLEDGE"],
    category: "PEOPLE",
    version: 1,
  },

  // -------------------------------------------------------------------------
  // Production extras (Dietary)
  // -------------------------------------------------------------------------
  {
    id: "FORECASTING",
    key: "FORECASTING",
    name: "Forecasting",
    description: "Production forecasting for meal and batch planning.",
    departments: ["DIETARY"],
    icon: "review",
    status: "active",
    tools: ["RECORDS", "FORMS"],
    category: "PRODUCTION",
    version: 1,
  },
  {
    id: "BATCH_RECORDS",
    key: "BATCH_RECORDS",
    name: "Batch Records",
    description: "Batch production records and yield documentation.",
    departments: ["DIETARY"],
    icon: "logs",
    status: "active",
    tools: ["RECORDS", "LOGS", "FORMS"],
    category: "PRODUCTION",
    version: 1,
  },

  // -------------------------------------------------------------------------
  // Quality / Compliance
  // -------------------------------------------------------------------------
  {
    id: "ROUNDING",
    key: "ROUNDING",
    name: "Rounding",
    description: "Structured supervisory and quality walkthroughs.",
    departments: ["DIETARY", "EVS", "PLANT"],
    icon: "review",
    status: "active",
    tools: ["FORMS", "TASKS", "RECORDS", "LOGS"],
    category: "QUALITY",
    version: 1,
  },
  {
    id: "SATISFACTION",
    key: "SATISFACTION",
    name: "Satisfaction",
    description: "Resident and guest satisfaction capture related to service.",
    departments: ["DIETARY"],
    icon: "review",
    status: "active",
    tools: ["FORMS", "RECORDS"],
    category: "QUALITY",
    version: 1,
  },
  {
    id: "AUDITS",
    key: "AUDITS",
    name: "Audits",
    description: "Compliance and quality audits across department areas.",
    departments: ["DIETARY", "EVS", "PLANT"],
    icon: "administration",
    status: "active",
    tools: ["FORMS", "RECORDS", "TASKS", "KNOWLEDGE"],
    category: "COMPLIANCE",
    version: 1,
  },
  {
    id: "INSPECTIONS",
    key: "INSPECTIONS",
    name: "Inspections",
    description: "Inspection programs, occurrences, and submissions.",
    departments: ["DIETARY", "EVS", "PLANT"],
    icon: "administration",
    status: "active",
    tools: ["FORMS", "RECORDS", "TASKS", "LOGS"],
    category: "COMPLIANCE",
    version: 1,
  },
  {
    id: "INFECTION_CONTROL",
    key: "INFECTION_CONTROL",
    name: "Infection Control",
    description: "Infection-control practices and verification for EVS.",
    departments: ["EVS"],
    icon: "administration",
    status: "active",
    tools: ["FORMS", "KNOWLEDGE", "LOGS", "TASKS"],
    category: "COMPLIANCE",
    version: 1,
  },
  {
    id: "LIFE_SAFETY",
    key: "LIFE_SAFETY",
    name: "Life Safety",
    description: "Life-safety compliance rounds and documentation for Plant.",
    departments: ["PLANT"],
    icon: "administration",
    status: "active",
    tools: ["LOGS", "FORMS", "RECORDS", "TASKS", "KNOWLEDGE"],
    category: "COMPLIANCE",
    version: 1,
  },
] as const;
