export {
  getLocationFunction,
  getLocationFunctionByKey,
  listLocationFunctionsForProduct,
  LOCATION_FUNCTIONS,
  resolveLocationFunctionAdoption,
  type LocationFunctionDefinition,
} from "./location-functions";
export {
  DEPARTMENT_PRODUCT_INDUSTRIES,
  DEPARTMENT_PRODUCT_KEYS,
  DEPARTMENT_PRODUCT_RELEASE_STATUSES,
  LEGACY_DEPARTMENT_PRODUCT_ALIASES,
  canonicalizeDepartmentProductKey,
  departmentProductKeysBelongToSameLineage,
  departmentProductLineageKeys,
  getDepartmentProduct,
  isCanonicalDepartmentProductKey,
  isDepartmentProductAvailableForInstall,
  isDepartmentProductCommerciallyRecognized,
  isDepartmentProductCustomerVisible,
  isDepartmentProductKey,
  isDepartmentProductOfferedForSale,
  isLegacyDepartmentProductAlias,
  listDepartmentProducts,
  listDepartmentProductsForIndustry,
  matchDepartmentRecordForProduct,
  matchEntitlementStatusForProduct,
  persistableDepartmentProductKey,
  resolveDepartmentProductForInstallationKey,
  type DepartmentProduct,
  type DepartmentProductDomainCapability,
  type DepartmentProductIndustry,
  type DepartmentProductKey,
  type DepartmentProductReferenceKey,
  type DepartmentProductReleaseStatus,
  type DepartmentProductStarterRefs,
  type DepartmentProductStatus,
  type LegacyDepartmentProductAlias,
} from "./registry";
export {
  departmentProductReleaseStatus,
  evaluateCustomerDepartmentOperability,
  evaluateDepartmentForAudience,
  hasInternalDepartmentProductAccess,
  customerCurrentDepartmentLabel,
  isCustomerCurrentDepartmentProductKey,
  marketplaceDenialReason,
  resolveCommercialEntitlement,
  shouldPresentDepartmentOnCustomerCurrentSurface,
  type BillingStatusForEntitlement,
  type DepartmentAccessAudience,
  type DepartmentOperability,
  type DepartmentOperabilityInput,
  type DepartmentOperabilityReason,
  type DepartmentPresentationAudience,
} from "./eligibility";
export {
  DepartmentProductInstallError,
  installDepartmentProduct,
  installDepartmentProductForInternalDevelopment,
  installResolvedDepartmentProduct,
  resolveDepartmentProductForInstall,
  resolveDepartmentProductForInternalInstall,
  resolvePublishedDepartmentProductKeys,
  type DepartmentProductInstallAudience,
  type DepartmentProductInstallErrorCode,
  type InstalledDepartmentProduct,
  type InstallDepartmentProductInput,
} from "./install";
export {
  cycleStarterWouldCreateCount,
  resolveCycleStarterForDepartmentProduct,
  type CycleStarterKind,
  type ResolvedCycleStarter,
} from "./cycle-starter";
export {
  canPurchaseDepartmentProducts,
  deriveFacilityDepartmentCatalog,
  findCatalogItemForDepartmentKey,
  groupCatalogByIndustry,
  industryCatalogLabel,
  availableToAddProductKeys,
  publishedCatalogProductKeys,
  selectOperableCatalogItems,
  type FacilityDepartmentCatalogItem,
  type FacilityDepartmentRecord,
  type FacilityEntitlementRecord,
} from "./facility-catalog";
export {
  loadCustomerOperableDepartments,
  loadDepartmentsForCurrentSurface,
  loadFacilityDepartmentAccessContext,
  loadFacilityDepartmentCatalog,
  selectCustomerOperableDepartments,
} from "./load-facility-catalog";
export {
  installDepartmentsForActiveEntitlements,
  shouldInstallLicensedDepartmentProducts,
} from "./reconcile";
